### PR TITLE
Fix README and add import logging.config

### PR DESCRIPTION
**Pull request by AndyLc**

### CODE REVIEW

**Comment by shankari** [comment]
ok to test

**Comment by shankari** [comment]
Failure was in 

```
======================================================================
FAIL: testZipCreation (netTests.TestProfile.TestProfile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/e-mission-server-prb/emission/tests/netTests/TestProfile.py", line 68, in testZipCreation
    self.assertEquals(prof_1['zip'],  '94720')
AssertionError: u'N/A' != '94720'
----------------------------------------------------------------------
```

This is clearly unrelated, but it would still be good to get a passing run before merging. Let me try running the test locally.

**Comment by shankari** [comment]
Not broken for local run (two checks). Probably a connection glitch. Retrying....

```
$ ./e-mission-py.bash emission/tests/netTests/TestProfile.py
----------------------------------------------------------------------
Ran 2 tests in 2.076s
```

**Comment by shankari** [comment]
jenkins, test this please

**Comment by shankari** [comment]
This time, the failure is in import. Note the lack of commits between previous failure and this one. Test infrastructure seems to have some issues. Will wait a couple of hours to see if it resolves, and ping shane otherwise.

```
+ ./runAllTests.sh
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.6/unittest.py", line 874, in <module>
    main(module=None)
  File "/usr/lib64/python2.6/unittest.py", line 815, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.6/unittest.py", line 842, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.6/unittest.py", line 848, in createTests
    self.module)
  File "/usr/lib64/python2.6/unittest.py", line 612, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.6/unittest.py", line 575, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named discover
```

**Comment by shankari** [comment]
jenkins, test this please

**Comment by shankari** [comment]
Same failure, emailed rise-support.

```
+ ./runAllTests.sh
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.6/unittest.py", line 874, in <module>
    main(module=None)
  File "/usr/lib64/python2.6/unittest.py", line 815, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.6/unittest.py", line 842, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.6/unittest.py", line 848, in createTests
    self.module)
  File "/usr/lib64/python2.6/unittest.py", line 612, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.6/unittest.py", line 575, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named discover
Build step 'Execute shell' marked build as failure
```

**Comment by shaneknapp** [comment]
test this please

**Comment by shankari** [comment]
Finally!

**Pull request merged**
