### PR TITLE
implemented yelp functions and tested with noise

### PR DESCRIPTION
**Pull request by trevor-wu**
—noise 0
INFO:root:Test complete, comparison results = 
INFO:root:candidate: find_destination_business_google, accuracy = 2.4390243902439024
INFO:root:candidate: find_destination_business_yelp, accuracy = 12.195121951219512
INFO:root:candidate: find_destination_business, accuracy = 19.51219512195122

—noise 10
INFO:root:Test complete, comparison results = 
INFO:root:candidate: find_destination_business_google, accuracy = 4.878048780487805
INFO:root:candidate: find_destination_business_yelp, accuracy = 12.195121951219512
INFO:root:candidate: find_destination_business, accuracy = 21.951219512195124

—noise 20
INFO:root:Test complete, comparison results = 
INFO:root:candidate: find_destination_business_google, accuracy = 2.4390243902439024
INFO:root:candidate: find_destination_business_yelp, accuracy = 14.634146341463415
INFO:root:candidate: find_destination_business, accuracy = 17.073170731707318

—noise 30
INFO:root:Test complete, comparison results = 
INFO:root:candidate: find_destination_business_google, accuracy = 2.4390243902439024
INFO:root:candidate: find_destination_business_yelp, accuracy = 12.195121951219512
INFO:root:candidate: find_destination_business, accuracy = 17.073170731707318

—noise 50
INFO:root:Test complete, comparison results = 
INFO:root:candidate: find_destination_business_google, accuracy = 0.0
INFO:root:candidate: find_destination_business_yelp, accuracy = 9.75609756097561
INFO:root:candidate: find_destination_business, accuracy = 12.195121951219512

Testing with noise, YELP API seems to work best around noise=20, but does not work as well as default. It does work consistently better than Google.

### CODE REVIEW

**Comment by shankari** [comment]
@trevor-wu 
> and an explanation of each failing test (e.g. the service returns xxx which doesn't have the information that we want. I experimented with a bunch of other parameters and they return yyy).

**Comment by shankari** [comment]
also, your changes should not involve anything other than the yelp functions - e.g. no change to 
`find_destination_business_nominatim` unless you can argue why it is a general change.

**Comment by trevor-wu** [comment]
`find_destination_business_nominatim ` was throwing errors when it returns a blank output so I was trying to fix that edge case.

**Comment by trevor-wu** [comment]
```
DEBUG:root:-----Manhattan Beach Kettle------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=33.8853681&longitude=-118.4097008&radius=50&limit=3 HTTP/1.1" 200 None

{'businesses': [{'id': '4OPXvjijT49v2aw_SSMSsA', 
'alias': 'the-kettle-manhattan-beach', 
'name': 'The Kettle', 
'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/La8NmKpRUz86_T8A822_GQ/o.jpg', 
'is_closed': False, 
'url': 'https://www.yelp.com/biz/the-kettle-manhattan-beach?adjust_creative=TJdz5Lnp0Vk5NdomBW6G1g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TJdz5Lnp0Vk5NdomBW6G1g', 
'review_count': 1497, 
'categories': [{'alias': 'diners', 'title': 'Diners'}, {'alias': 'tradamerican', 'title': 'American (Traditional)'}], 'rating': 4.0, 'coordinates': {'latitude': 33.8853351121315, 'longitude': -118.40965713508}, 'transactions': ['pickup', 'delivery'], 'price': '$$', 'location': {'address1': '1138 Highland Ave', 'address2': '', 'address3': '', 'city': 'Manhattan Beach', 'zip_code': '90266', 'country': 'US', 'state': 'CA', 'display_address': ['1138 Highland Ave', 'Manhattan Beach, CA 90266']}, 'phone': '+13105458511', 'display_phone': '(310) 545-8511', 'distance': 5.449865640596009}, {'id': 'EEP1Q4v-GyyStaPlI1r6fA', 'alias': 'simmzys-manhattan-beach-3', 'name': "Simmzy's", 'image_url': 'https://s3-media1.fl.yelpcdn.com/bphoto/wx3retElAUla8wZ60qHHgQ/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/simmzys-manhattan-beach-3?adjust_creative=TJdz5Lnp0Vk5NdomBW6G1g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TJdz5Lnp0Vk5NdomBW6G1g', 'review_count': 1137, 'categories': [{'alias': 'pubs', 'title': 'Pubs'}, {'alias': 'newamerican', 'title': 'American (New)'}, {'alias': 'gastropubs', 'title': 'Gastropubs'}], 'rating': 4.0, 'coordinates': {'latitude': 33.885174, 'longitude': -118.410023}, 'transactions': [], 'price': '$$', 'location': {'address1': '229 Manhattan Beach Blvd', 'address2': '', 'address3': '', 'city': 'Manhattan Beach', 'zip_code': '90266', 'country': 'US', 'state': 'CA', 'display_address': ['229 Manhattan Beach Blvd', 'Manhattan Beach, CA 90266']}, 'phone': '+13105461201', 'display_phone': '(310) 546-1201', 'distance': 36.74787197143011}, {'id': '59BdaTnmT9wdW1E4ILywPg', 'alias': 'the-izaka-ya-by-katsu-ya-manhattan-beach-manhattan-beach', 'name': 'The Izaka-Ya by Katsu-Ya Manhattan Beach', 'image_url': 'https://s3-media2.fl.yelpcdn.com/bphoto/JN_cTwyxRi3AM8Qsh5HBkQ/o.jpg', 'is_closed': False, 'url': 'https://www.yelp.com/biz/the-izaka-ya-by-katsu-ya-manhattan-beach-manhattan-beach?adjust_creative=TJdz5Lnp0Vk5NdomBW6G1g&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=TJdz5Lnp0Vk5NdomBW6G1g', 'review_count': 860, 'categories': [{'alias': 'sushi', 'title': 'Sushi Bars'}, {'alias': 'japanese', 'title': 'Japanese'}], 'rating': 4.0, 'coordinates': {'latitude': 33.885335, 'longitude': -118.40996}, 'transactions': ['restaurant_reservation'], 'price': '$$', 'location': {'address1': '1133 Highland Ave', 'address2': '', 'address3': '', 'city': 'Manhattan Beach', 'zip_code': '90266', 'country': 'US', 'state': 'CA', 'display_address': ['1133 Highland Ave', 'Manhattan Beach, CA 90266']}, 'phone': '+13107961888', 'display_phone': '(310) 796-1888', 'distance': 24.207897896326568}], 'total': 10, 'region': {'center': {'longitude': -118.4097008, 'latitude': 33.8853681}}}
('The Kettle', '1138 Highland Ave', 'Manhattan Beach', True)
DEBUG:root:no match! name = The Kettle, comparing with ['Kettle', 'North Highland Avenue', True]
DEBUG:root:Test Manhattan Beach Kettle failed, output = False, expected ['Kettle', 'North Highland Avenue', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Manhattan Beach Kettle, successfulTests = 0, failedTests = 2
```
This test failed because the test case forgot "The" in the name

**Comment by trevor-wu** [comment]
DEBUG:root:-----Manhattan Beach Beckers------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=33.884278&longitude=-118.4106739&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [{'id': 'oclpV2d1KGl1Zi80sFt5QA', 'alias': 'rockn-fish-manhattan-beach', 'name': "Rock'N Fish"}, {'id': 'wfI_0zcs1u1f9YvfeKoaiw', 'alias': 'manhattan-beach-creamery-manhattan-beach', 'name': 'Manhattan Beach Creamery', }, {'id': 'GHu47QaHNPm1IEBFwgfjsQ', 'alias': 'ercoles-1101-manhattan-beach-2', 'name': 'Ercoles 1101'}
("Rock'N Fish", '120 Manhattan Beach Blvd', 'Manhattan Beach', True)
DEBUG:root:no match! name = Rock'N Fish, comparing with ["Becker's Bakery and Deli", 'Manhattan Beach Ave', 'Manhattan Beach', True]
DEBUG:root:Test Manhattan Beach Beckers failed, output = False, expected ["Becker's Bakery and Deli", 'Manhattan Beach Ave', 'Manhattan Beach', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Manhattan Beach Beckers, successfulTests = 0, failedTests = 3
Screen Shot 2019-04-28 at 7 43 54 PM
Does not seem to work too well in dense shopping areas, lat/lon might not be too accurate.

**Comment by trevor-wu** [comment]
```
DEBUG:root:-----Mira Costa High School Manhattan Beach------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=33.8729666&longitude=-118.3893806&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -118.3893806, 'latitude': 33.8729666}}}
DEBUG:root:no match! name = None, comparing with ['Mira Costa High School', 'Artesia Boulevard', 'Manhattan Beach', True]
DEBUG:root:Test Mira Costa High School Manhattan Beach failed, output = False, expected ['Mira Costa High School', 'Artesia Boulevard', 'Manhattan Beach', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Mira Costa High School Manhattan Beach, successfulTests = 0, failedTests = 7
```
Most common fail case is where Yelp fails to query any businesses. It also fails with El Segundo HS, San Ramon valley HS, and MSJHS. Also fails to query at large stores and hospitals.

**Comment by trevor-wu** [comment]
```
DEBUG:root:-----99 Ranch Market Fremont------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.4881864&longitude=-121.9309053&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -121.9309053, 'latitude': 37.4881864}}}
DEBUG:root:no match! name = None, comparing with ['99 Ranch Market', 'Warm Springs Boulevard', 'Fremont', True]
DEBUG:root:Test 99 Ranch Market Fremont failed, output = False, expected ['99 Ranch Market', 'Warm Springs Boulevard', 'Fremont', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance 99 Ranch Market Fremont, successfulTests = 5, failedTests = 28
DEBUG:root:-----Mission San Jose High School Fremont------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.5443018&longitude=-121.935992&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -121.935992, 'latitude': 37.5443018}}}
DEBUG:root:no match! name = None, comparing with ['Mission San Jose High School', 'Palm Avenue', 'Fremont', True]
DEBUG:root:Test Mission San Jose High School Fremont failed, output = False, expected ['Mission San Jose High School', 'Palm Avenue', 'Fremont', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Mission San Jose High School Fremont, successfulTests = 5, failedTests = 29
DEBUG:root:-----Giraffe Learning Center------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.5417558&longitude=-121.9485068&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -121.9485068, 'latitude': 37.5417558}}}
DEBUG:root:no match! name = None, comparing with ['Giraffe Learning Center', 'Driscoll Road', 'Fremont', True]
DEBUG:root:Test Giraffe Learning Center failed, output = False, expected ['Giraffe Learning Center', 'Driscoll Road', 'Fremont', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Giraffe Learning Center, successfulTests = 5, failedTests = 30
DEBUG:root:-----Costco------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.5016114&longitude=-121.9752093&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -121.9752093, 'latitude': 37.5016114}}}
DEBUG:root:no match! name = None, comparing with ['Costco', 'Pacific Commons Boulevard', 'Fremont', True]
DEBUG:root:Test Costco failed, output = False, expected ['Costco', 'Pacific Commons Boulevard', 'Fremont', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Costco, successfulTests = 5, failedTests = 31
DEBUG:root:-----Ohlone College------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.5298962&longitude=-121.9168524&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -121.9168524, 'latitude': 37.5298962}}}
DEBUG:root:no match! name = None, comparing with ['Ohlone College', 'Mission Boulevard', 'Fremont', True]
DEBUG:root:Test Ohlone College failed, output = False, expected ['Ohlone College', 'Mission Boulevard', 'Fremont', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Ohlone College, successfulTests = 5, failedTests = 32
DEBUG:root:-----Holiday Inn San Jose - Silicon Valley------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.361147&longitude=-121.9099833&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -121.9099833, 'latitude': 37.361147}}}
DEBUG:root:no match! name = None, comparing with ['Holiday Inn San Jose - Silicon Valley', 'North 1st Street', 'San Jose', True]
DEBUG:root:Test Holiday Inn San Jose - Silicon Valley failed, output = False, expected ['Holiday Inn San Jose - Silicon Valley', 'North 1st Street', 'San Jose', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Holiday Inn San Jose - Silicon Valley, successfulTests = 5, failedTests = 33
DEBUG:root:-----Annie Hair & Beauty------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.4891932&longitude=-121.9318015&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -121.9318015, 'latitude': 37.4891932}}}
DEBUG:root:no match! name = None, comparing with ['Annie Hair & Beauty', 'Warm Springs Boulevard', 'Fremont', True]
DEBUG:root:Test Annie Hair & Beauty failed, output = False, expected ['Annie Hair & Beauty', 'Warm Springs Boulevard', 'Fremont', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Annie Hair & Beauty, successfulTests = 5, failedTests = 34
DEBUG:root:-----Quik Stop------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.5307587&longitude=-121.9392133&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -121.9392133, 'latitude': 37.5307587}}}
DEBUG:root:no match! name = None, comparing with ['Quik Stop', 'Washington Boulevard', 'Fremont', True]
DEBUG:root:Test Quik Stop failed, output = False, expected ['Quik Stop', 'Washington Boulevard', 'Fremont', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Quik Stop, successfulTests = 5, failedTests = 35
DEBUG:root:-----Department of Motor Vehicles------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?latitude=37.5533451&longitude=-122.0093908&radius=50&limit=3 HTTP/1.1" 200 None
{'businesses': [], 'total': 0, 'region': {'center': {'longitude': -122.0093908, 'latitude': 37.5533451}}}
DEBUG:root:no match! name = None, comparing with ['Department of Motor Vehicles', 'Central Avenue', 'Fremont', True]
DEBUG:root:Test Department of Motor Vehicles failed, output = False, expected ['Department of Motor Vehicles', 'Central Avenue', 'Fremont', True] 
DEBUG:root:For candidate find_destination_business_yelp, after instance Department of Motor Vehicles, successfulTests = 5, failedTests = 36
INFO:root:Testing candidate find_destination_business_yelp complete, overall accuracy = 12.195121951219512 
```
All these are in sparser suburban areas, and yelp seems to fail to query with a 50m search radius from the lat,lon.

**Comment by trevor-wu** [comment]
I only tested with google, yelp, and original because find_business_with_nominatim was throwing this error on some test cases:
```
DEBUG:root:-----Manhattan Beach Kettle------
INFO:root:noise_in_meters = 0, skipping add_noise
DEBUG:root:For reverse geocoding, using URL http://54.198.41.236/nominatim/reverse?lat=33.8853681&lon=-118.4097008&format=json
DEBUG:root:parsed_response = {'place_id': '618259', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'lat': '33.8902051321443', 'lon': '-118.401916494028', 'display_name': '90266, United States of America', 'address': {'postcode': '90266', 'country': 'United States of America', 'country_code': 'us'}}
Traceback (most recent call last):
  File "emission/integrationTests/suggestionsys/algorithm_test_harness.py", line 178, in <module>
    result = test_single_instance(test_fn, cfn, instance, args.noise)
  File "emission/integrationTests/suggestionsys/algorithm_test_harness.py", line 79, in test_single_instance
    result = test_fn(cfn, param, exp_output, noise_in_meters)
  File "emission/integrationTests/suggestionsys/algorithm_test_harness.py", line 45, in test_find_destination_business
    result = cfn(lat, lon)
  File "/Users/trevorwu/urap-2018/urap2018-2019/e-mission-server/emission/core/wrapper/suggestion_sys.py", line 219, in find_destination_business_nominatim
    city = address_dict['city']
KeyError: 'city'
```

**Comment by shankari** [comment]
superceded by #685

**Pull request closed without merging**
