### PR TITLE
added new qr control code

### PR DESCRIPTION
**Pull request by sam11b**
Updated qr control code to our studies qr control group and not last semester's. Apologies this was incorrect before.

### CODE REVIEW

**Comment by shankari** [comment]
@sam11b can you add the testing done?

**Comment by sam11b** [comment]
Would you like this in the form of a video link like last time?

**Comment by shankari** [comment]
yeah video link would be good

**Comment by sam11b** [comment]
https://youtu.be/PoO8kOQJWM4 

I've cropped out my email password but as you can see I was given the control QR code and it was generated correctly.

**Pull request merged**
