### PR TITLE
Changed other files corresponding to the profile.py change

### PR DESCRIPTION
**Pull request by Mogeng**

### CODE REVIEW

**Comment by shankari** [comment]
ok to test

**Comment by Mogeng** [comment]
I know what cause the previous test to fail. It was because the lat lon order. In the very very original version, it was (lat, lon). I don’t know why in “some of” the scripts and test cases, it was changed to (lon, lat), while the other scripts were still (lat, lon). That is what caused the discrepancy and you will have either previous test fail or profile.py fail.

We need to agree on the order of (lat, lon) or (lon, lat).

Mogeng

**Comment by shankari** [comment]
We changed it to (lat, lon) last summer in order to match the geojson format, which is the format that mongodb stores the data in.
http://geojson.org/geojson-spec.html
> The order of elements must follow x, y, z order (easting, northing, altitude for coordinates in a projected coordinate reference system, or longitude, latitude, altitude for coordinates in a geographic coordinate reference system).

I believe that at that time, we changed all the scripts to deal with this ordering.

> commit 393134535e1a8408d0e24b0c6ab1c2b7338f2718
> Author: K. Shankari <shankari@eecs.berkeley.edu>
> Date:   Fri Aug 22 23:08:56 2014 -0700

> Swith the trackpoints to (lng, lat) to match the GeoJSON format.
> This is the server side - changes to the phone app are upcoming.

**Comment by Mogeng** [comment]
Ok, so I will change everything later to lon, lat and write the new test
cases.


On Mar 16, 2015, at 21:18, shankari <notifications@github.com> wrote:

We changed it to (lat, lon) last summer in order to match the geojson
format, which is the format that mongodb stores the data in.
http://geojson.org/geojson-spec.html

The order of elements must follow x, y, z order (easting, northing,
altitude for coordinates in a projected coordinate reference system, or
longitude, latitude, altitude for coordinates in a geographic coordinate
reference system).

I believe that at that time, we changed all the scripts to deal with this
ordering.

commit 393134535e1a8408d0e24b0c6ab1c2b7338f2718
Author: K. Shankari shankari@eecs.berkeley.edu
Date: Fri Aug 22 23:08:56 2014 -0700

Swith the trackpoints to (lng, lat) to match the GeoJSON format.
This is the server side - changes to the phone app are upcoming.

—
Reply to this email directly or view it on GitHub
<https://github.com/e-mission/e-mission-server/pull/105#issuecomment-82096161>
.

**Comment by shankari** [comment]
And now you see why automated test cases are good :)

We now have a simple script that will run all the automated test cases (`e-mission-server/runAllTests.sh`). You might want to run that before pushing additional changes.

**Comment by Mogeng** [comment]
Sure, that will be good!

On Mar 16, 2015, at 21:24, shankari <notifications@github.com> wrote:

And now you see why automated test cases are good :)

We now have a simple script that will run all the automated test cases (
e-mission-server/runAllTests.sh). You might want to run that before pushing
additional changes.

—
Reply to this email directly or view it on GitHub
<https://github.com/e-mission/e-mission-server/pull/105#issuecomment-82096946>
.

**Pull request closed without merging**
