### PR TITLE
Improving Trip Segmentation

### PR DESCRIPTION
**Pull request by humbleOldSage**
Reducing DB calls. Using more in memory operations.

### CODE REVIEW

**Comment by humbleOldSage** [comment]
Tested. Will fail.

**Comment by shankari** [comment]
@humbleOldSage can ypu:
- split the two improvements into separate PRs?
- add high quality commit messages that (i) quantify the improvements and (ii) link to the issue where you performed the investigation?

This will let me chose which of the improvements to merge. Making server changes can introduce code churn, and I am not convinced that the invalidating raw entry change (which involves a change to the timeseries interface) is worth it.

**Comment by humbleOldSage** [comment]
Sure. I'll create two separate PRs for these two changes.

**Comment by humbleOldSage** [comment]
All the changes here are now split into two separate PRs :

https://github.com/e-mission/e-mission-server/pull/956 -- for reducing DB calls.
https://github.com/e-mission/e-mission-server/pull/957. -- for improved invalidation.

There will no longer be any changes here.

**Comment by shankari** [comment]
@humbleOldSage if this has been replaced by other calls, can you please close this PR?

**Comment by humbleOldSage** [comment]
Sure.

**Pull request closed without merging**
