### PR TITLE
Closes e-mission/e-mission-docs#813

### PR DESCRIPTION
**Pull request by asiripanich**

### CODE REVIEW

**Comment by shankari** [comment]
@asiripanich can you confirm that this does fix the issue?

**Comment by shankari** [comment]
Just for my own edification, I wanted to see how I didn't catch this in testing.
This is the related change
https://github.com/e-mission/e-mission-server/commit/dda42c0e431c6572fff44e97fd2b8c1b4c267995

I tested the demographic survey but not the trip survey and assumed that the trip survey was similar...

**Comment by asiripanich** [comment]
Partially fixed?

IMG_18BDC6AD9545-1

**Comment by asiripanich** [comment]
@shankari other than 
- https://github.com/e-mission/e-mission-docs/commit/9132bd753e10bef3f5700a44d9719f81d02e71a9 and
- https://github.com/e-mission/e-mission-docs/issues/793#issuecomment-1274039517

are there anything else I need to do to make the ENKETO survey feature works?

**Comment by asiripanich** [comment]
@shankari any thoughts on this?

**Comment by shankari** [comment]
@asiripanich it is on my queue of things to work on. Sorry, was busy with quarterly reviews this week.

**Comment by shankari** [comment]
finally got done with all admin stuff.
Checking your logs to see what is going on and whether I can reproduce.

**Comment by asiripanich** [comment]
🎉 happy to help with testing and debugging if needed :)

**Comment by shankari** [comment]
The logs here are not fully complete, but I do see the following calls to the server

```
987,1665487512.6445699,2022-10-11T04:25:12.644570-07:00,Application will enter the foreground
991,1665487540.38217,2022-10-11T04:25:40.382170-07:00,postToHost called with url = https://emission-app.fourstep.dev/pipeline/get_complete_ts
995,1665487540.92151,2022-10-11T04:25:40.921510-07:00,postToHost called with url = https://emission-app.fourstep.dev/datastreams/find_entries/timestamp
998,1665487540.92626,2022-10-11T04:25:40.926260-07:00,postToHost called with url = https://emission-app.fourstep.dev/timeline/getTrips/2022-10-11
1001,1665487542.04632,2022-10-11T04:25:42.046320-07:00,"while reading data for 1665406800000 from server, got nTrips = 3"
1002,1665487542.05253,2022-10-11T04:25:42.052530-07:00,"found 3 trips, last_processed_ts = Tue Oct 11 2022 21:32:42 GMT+1100"
```

we then read the transitions to recreate unprocessed trips and there are none.

```
1003,1665487542.0541,2022-10-11T04:25:42.054100-07:00,about to query for unprocessed trips from Tue Oct 11 2022 21:32:42 GMT+1100 -> Tue Oct 11 2022 23:59:59 GMT+1100
1006,1665487542.05822,2022-10-11T04:25:42.058220-07:00,postToHost called with url = https://emission-app.fourstep.dev/datastreams/find_entries/timestamp
1007,1665487542.54758,2022-10-11T04:25:42.547580-07:00,About to dedup localResult = 2remoteResult = 4
1008,1665487542.55448,2022-10-11T04:25:42.554480-07:00,Deduped list = 6
1009,1665487542.55625,2022-10-11T04:25:42.556250-07:00,Found 6 transitions. yay!
1010,1665487542.5576801,2022-10-11T04:25:42.557680-07:00,"No further unprocessed trips started, exiting loop"
1011,1665487542.55933,2022-10-11T04:25:42.559330-07:00,Mapped into0 trips. yay!
```

I don't see what is returned from the server.

Can you check the trips in the server to see whether they do have the `userInput` values filled in?

**Comment by asiripanich** [comment]
All of the trips I made on 11 Oct 2022 now have the `userInput` values filled. However, at the time that I sent you the log, I had only responded to the trip end surveys of the first two trips.

```json
{
    "_id" : ObjectId("634523b4ee2f29181cf5e4ac"),
    "user_id" : LUUID("XXXXXX"),
    "metadata" : {
        "key" : "analysis/confirmed_trip",
        "platform" : "server",
        "write_ts" : 1665475508.301799,
        "time_zone" : "America/Los_Angeles",
        "write_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(1),
            "minute" : NumberInt(5),
            "second" : NumberInt(8),
            "weekday" : NumberInt(1),
            "timezone" : "America/Los_Angeles"
        },
        "write_fmt_time" : "2022-10-11T01:05:08.301799-07:00"
    },
    "data" : {
        "source" : "DwellSegmentationDistFilter",
        "end_ts" : 1665474539.9999347,
        "end_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(18),
            "minute" : NumberInt(48),
            "second" : NumberInt(59),
            "weekday" : NumberInt(1),
            "timezone" : "Australia/Sydney"
        },
        "end_fmt_time" : "2022-10-11T18:48:59.999935+11:00",
        "end_loc" : {
            "type" : "Point",
            "coordinates" : [
                151.24264343413776,
                -33.919993492312344
            ]
        },
        "raw_trip" : ObjectId("634523b2ee2f29181cf5e45b"),
        "start_ts" : 1665472861.12776,
        "start_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(18),
            "minute" : NumberInt(21),
            "second" : NumberInt(1),
            "weekday" : NumberInt(1),
            "timezone" : "Australia/Sydney"
        },
        "start_fmt_time" : "2022-10-11T18:21:01.127760+11:00",
        "start_loc" : {
            "type" : "Point",
            "coordinates" : [
                151.23455183428112,
                -33.91654937309654
            ]
        },
        "duration" : 1678.8721747398376,
        "distance" : 1046.6623027585865,
        "start_place" : ObjectId("634523b4ee2f29181cf5e4a0"),
        "end_place" : ObjectId("634523b4ee2f29181cf5e4a1"),
        "cleaned_trip" : ObjectId("634523b3ee2f29181cf5e465"),
        "inferred_labels" : [

        ],
        "inferred_trip" : ObjectId("634523b4ee2f29181cf5e4a6"),
        "expectation" : {
            "to_label" : true
        },
        "confidence_threshold" : 0.55,
        "expected_trip" : ObjectId("634523b4ee2f29181cf5e4aa"),
        "user_input" : {
            "trip_user_input" : "1 purpose, 1 mode"
        }
    }
}
{
    "_id" : ObjectId("634531c1ce98ccc67e2348fd"),
    "user_id" : LUUID("XXXXXX"),
    "metadata" : {
        "key" : "analysis/confirmed_trip",
        "platform" : "server",
        "write_ts" : 1665479105.6969206,
        "time_zone" : "America/Los_Angeles",
        "write_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(2),
            "minute" : NumberInt(5),
            "second" : NumberInt(5),
            "weekday" : NumberInt(1),
            "timezone" : "America/Los_Angeles"
        },
        "write_fmt_time" : "2022-10-11T02:05:05.696921-07:00"
    },
    "data" : {
        "source" : "DwellSegmentationDistFilter",
        "end_ts" : 1665477485.0268362,
        "end_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(19),
            "minute" : NumberInt(38),
            "second" : NumberInt(5),
            "weekday" : NumberInt(1),
            "timezone" : "Australia/Sydney"
        },
        "end_fmt_time" : "2022-10-11T19:38:05.026836+11:00",
        "end_loc" : {
            "type" : "Point",
            "coordinates" : [
                151.24012785637078,
                -33.915624621196834
            ]
        },
        "raw_trip" : ObjectId("634531c0ce98ccc67e2348d7"),
        "start_ts" : 1665477031.243856,
        "start_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(19),
            "minute" : NumberInt(30),
            "second" : NumberInt(31),
            "weekday" : NumberInt(1),
            "timezone" : "Australia/Sydney"
        },
        "start_fmt_time" : "2022-10-11T19:30:31.243856+11:00",
        "start_loc" : {
            "type" : "Point",
            "coordinates" : [
                151.24264343413776,
                -33.919993492312344
            ]
        },
        "duration" : 453.78298020362854,
        "distance" : 591.5602109424055,
        "start_place" : ObjectId("634523b4ee2f29181cf5e4a1"),
        "end_place" : ObjectId("634531c1ce98ccc67e2348f2"),
        "cleaned_trip" : ObjectId("634531c1ce98ccc67e2348de"),
        "inferred_labels" : [

        ],
        "inferred_trip" : ObjectId("634531c1ce98ccc67e2348f7"),
        "expectation" : {
            "to_label" : true
        },
        "confidence_threshold" : 0.55,
        "expected_trip" : ObjectId("634531c1ce98ccc67e2348fb"),
        "user_input" : {
            "trip_user_input" : "Trip not valid"
        }
    }
}
{
    "_id" : ObjectId("63454de1680009612b7ba5fd"),
    "user_id" : LUUID("XXXXXX"),
    "metadata" : {
        "key" : "analysis/confirmed_trip",
        "platform" : "server",
        "write_ts" : 1665486305.2498436,
        "time_zone" : "America/Los_Angeles",
        "write_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(4),
            "minute" : NumberInt(5),
            "second" : NumberInt(5),
            "weekday" : NumberInt(1),
            "timezone" : "America/Los_Angeles"
        },
        "write_fmt_time" : "2022-10-11T04:05:05.249844-07:00"
    },
    "data" : {
        "source" : "DwellSegmentationDistFilter",
        "end_ts" : 1665484362.0157437,
        "end_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(21),
            "minute" : NumberInt(32),
            "second" : NumberInt(42),
            "weekday" : NumberInt(1),
            "timezone" : "Australia/Sydney"
        },
        "end_fmt_time" : "2022-10-11T21:32:42.015744+11:00",
        "end_loc" : {
            "type" : "Point",
            "coordinates" : [
                151.20338525298746,
                -33.87713727757504
            ]
        },
        "raw_trip" : ObjectId("63454de0680009612b7ba5d5"),
        "start_ts" : 1665483928.777565,
        "start_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(11),
            "hour" : NumberInt(21),
            "minute" : NumberInt(25),
            "second" : NumberInt(28),
            "weekday" : NumberInt(1),
            "timezone" : "Australia/Sydney"
        },
        "start_fmt_time" : "2022-10-11T21:25:28.777565+11:00",
        "start_loc" : {
            "type" : "Point",
            "coordinates" : [
                151.2058604620818,
                -33.88157954231861
            ]
        },
        "duration" : 433.238178730011,
        "distance" : 714.1838147842788,
        "start_place" : ObjectId("63454de1680009612b7ba5f1"),
        "end_place" : ObjectId("63454de1680009612b7ba5f2"),
        "cleaned_trip" : ObjectId("63454de0680009612b7ba5df"),
        "inferred_labels" : [

        ],
        "inferred_trip" : ObjectId("63454de1680009612b7ba5f7"),
        "expectation" : {
            "to_label" : true
        },
        "confidence_threshold" : 0.55,
        "expected_trip" : ObjectId("63454de1680009612b7ba5fb"),
        "user_input" : {
            "trip_user_input" : "1 purpose, 1 mode"
        }
    }
}
```

**Comment by shankari** [comment]
so I think this is the problem

the `user_input` is set to 

```
        "user_input" : {
            "trip_user_input" : "1 purpose, 1 mode"
        }
```

so when we try to parse it after we retrieve it, we clearly don't get anything

**Comment by shankari** [comment]
This is because when we do the user matching, we only copy over the label.

```
            input_name = obj_to_dict_key(ui.metadata.key)
            confirmed_trip["data"]["user_input"][input_name] = ui.data.label
```

**Comment by asiripanich** [comment]
I guess we need to fix it here then?

https://github.com/e-mission/e-mission-server/blob/ed2adbbf709f863ca7ab29b098ad7da170ded206/emission/analysis/userinput/matcher.py#L39-L43

**Comment by shankari** [comment]
I am just trying to figure out what the phone expects.
Also I am pretty sure that this is wrong `if input_name == "trip_user_input"`, I expect that it would be `manual/trip_user_input` instead

**Comment by asiripanich** [comment]
>  Also I am pretty sure that this is wrong if input_name == "trip_user_input", I expect that it would be manual/trip_user_input instead

You are right it should by `manual/trip_user_input`

```json
    "_id" : ObjectId("633f7587f6694ea8a722f1df"),
    "user_id" : LUUID("XXXX"),
    "metadata" : {
        "time_zone" : "Australia/Sydney",
        "plugin" : "none",
        "write_ts" : 1665064249.61109,
        "platform" : "ios",
        "read_ts" : NumberInt(0),
        "key" : "manual/trip_user_input",
        "type" : "message",
        "write_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(7),
            "hour" : NumberInt(0),
            "minute" : NumberInt(50),
            "second" : NumberInt(49),
            "weekday" : NumberInt(4),
            "timezone" : "Australia/Sydney"
        },
        "write_fmt_time" : "2022-10-07T00:50:49.611090+11:00"
    },
    "data" : {
        "end_ts" : 1665053698.613543,
        "xmlResponse" : "<data xmlns:jr=\"http://openrosa.org/javarosa\" xmlns:odk=\"http://www.opendatakit.org/xforms\" xmlns:orx=\"http://openrosa.org/xforms\" id=\"snapshot_xml\">\n          <start>2022-10-07T00:50:48.022+11:00</start>\n          <end>2022-10-07T00:50:48.023+11:00</end>\n          <destination_purpose>trip_not_valid</destination_purpose>\n          <travel_mode/>\n          <Total_people_in_trip_party/>\n          <Non_household_member_s_on_trip/>\n          <Vehicle_trip_Parking_location>1</Vehicle_trip_Parking_location>\n          <Parking_cost>0</Parking_cost>\n          <Total_toll_charges_p_uring_the_trip_AUD>0</Total_toll_charges_p_uring_the_trip_AUD>\n          <Transit_fees_AUD/>\n          <Taxi_fees/>\n          <meta>\n            <instanceID>uuid:b3d022c3-e4ed-429e-8eed-e1cd3d9c5183</instanceID>\n          </meta>\n        </data>",
        "label" : "Trip not valid",
        "jsonDocResponse" : {
            "data" : {
                "Parking_cost" : "0",
                "start" : "2022-10-07T00:50:48.022+11:00",
                "travel_mode" : "",
                "Total_toll_charges_p_uring_the_trip_AUD" : "0",
                "Vehicle_trip_Parking_location" : "1",
                "Total_people_in_trip_party" : "",
                "Transit_fees_AUD" : "",
                "destination_purpose" : "trip_not_valid",
                "meta" : {
                    "attr" : {

                    },
                    "instanceID" : "uuid:b3d022c3-e4ed-429e-8eed-e1cd3d9c5183"
                },
                "Taxi_fees" : "",
                "end" : "2022-10-07T00:50:48.023+11:00",
                "Non_household_member_s_on_trip" : "",
                "attr" : {
                    "xmlns:orx" : "http://openrosa.org/xforms",
                    "id" : "snapshot_xml",
                    "xmlns:odk" : "http://www.opendatakit.org/xforms",
                    "xmlns:jr" : "http://openrosa.org/javarosa"
                }
            }
        },
        "start_ts" : 1665053285.060921,
        "name" : "TripConfirmSurvey",
        "version" : 1.2,
        "start_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(6),
            "hour" : NumberInt(21),
            "minute" : NumberInt(48),
            "second" : NumberInt(5),
            "weekday" : NumberInt(3),
            "timezone" : "Australia/Sydney"
        },
        "start_fmt_time" : "2022-10-06T21:48:05.060921+11:00",
        "end_local_dt" : {
            "year" : NumberInt(2022),
            "month" : NumberInt(10),
            "day" : NumberInt(6),
            "hour" : NumberInt(21),
            "minute" : NumberInt(54),
            "second" : NumberInt(58),
            "weekday" : NumberInt(3),
            "timezone" : "Australia/Sydney"
        },
        "end_fmt_time" : "2022-10-06T21:54:58.613543+11:00"
    }
```

**Comment by asiripanich** [comment]
> obj_to_dict_key

I see `obj_to_dict_key = lambda key: key.split("/")[1]`.

**Comment by shankari** [comment]
on the phone, we first get any unprocessed entry
if it doesn't exist, we get the processed entry
then we call `populateInput`

```
      const unprocessedLabelEntry = InputMatcher.getUserInputForTrip(trip, nextTrip,
          inputList);
      var userInputEntry = unprocessedLabelEntry;
      if (!angular.isDefined(userInputEntry)) {
          userInputEntry = trip.user_input[etbs.inputType2retKey(inputType)];
      }
      etbs.populateInput(trip.userInput, inputType, userInputEntry);
```

**Comment by shankari** [comment]
I think that for the enketo case, you actually do want to set the entire entry and not just the data - e.g.

```
if input_name == "trip_user_input":
     confirmed_trip["data"]["user_input"][input_name] = ui
```

Here's the reason why:
we read the value from the `user_input` and call `populateInput`

```
      if (!angular.isDefined(userInputEntry)) {
          userInputEntry = trip.user_input[etbs.inputType2retKey(inputType)];
      }
      etbs.populateInput(trip.userInput, inputType, userInputEntry);
```

which just sets the value without modification into `trip.userInput`

```
  etbs.populateInput = function(tripField, inputType, userInputEntry) {
    if (angular.isDefined(userInputEntry)) {
        tripField[inputType] = userInputEntry;
    }
  }
```

and when we populate the answer, we use `answer.data.xmlResponse` not `answer.xmlResponse`

```
  function _restoreAnswer() {
    if (_state.opts.trip) {
      const answer = _state.opts.trip.userInput["SURVEY"];
      return answer ? answer.data.xmlResponse : null;
```

Of course, if it turns out that I am wrong, go back to your suggestion 😄

**Comment by asiripanich** [comment]
> I think that for the enketo case, you actually do want to set the entire entry and not just the data - e.g.
> 
> ```
> if input_name == "trip_user_input":
>      confirmed_trip["data"]["user_input"][input_name] = ui
> ```
> 
> Here's the reason why: we read the value from the `user_input` and call `populateInput`
> 
> ```
>       if (!angular.isDefined(userInputEntry)) {
>           userInputEntry = trip.user_input[etbs.inputType2retKey(inputType)];
>       }
>       etbs.populateInput(trip.userInput, inputType, userInputEntry);
> ```
> 
> which just sets the value without modification into `trip.userInput`
> 
> ```
>   etbs.populateInput = function(tripField, inputType, userInputEntry) {
>     if (angular.isDefined(userInputEntry)) {
>         tripField[inputType] = userInputEntry;
>     }
>   }
> ```
> 
> and when we populate the answer, we use `answer.data.xmlResponse` not `answer.xmlResponse`
> 
> ```
>   function _restoreAnswer() {
>     if (_state.opts.trip) {
>       const answer = _state.opts.trip.userInput["SURVEY"];
>       return answer ? answer.data.xmlResponse : null;
> ```
> 
> Of course, if it turns out that I am wrong, go back to your suggestion 😄

Would you like me to submit a PR to fix this?

**Comment by asiripanich** [comment]
Testing the fix right now. I just reset the pipeline state and re-running the pipeline intake.

**Comment by shankari** [comment]
@asiripanich did it work?

**Comment by shankari** [comment]
If it did work, yes, I would like you to include the second commit in this PR as well.

**Comment by asiripanich** [comment]
It doesn't work. I'm going ti test everything again in an emulator and a local server.

**Comment by asiripanich** [comment]
> @shankari other than 
> 
> - https://github.com/e-mission/e-mission-docs/commit/9132bd753e10bef3f5700a44d9719f81d02e71a9 and
> 
> - https://github.com/e-mission/e-mission-docs/issues/793#issuecomment-1274039517
> 
> 
> 
> are there anything else I need to do to make the ENKETO survey feature works?

@shankari could you please confirm that these are all the setup i need?

**Comment by shankari** [comment]
> It doesn't work. I'm going ti test everything again in an emulator and a local server.

In what way does it not work?

**Comment by asiripanich** [comment]
> > It doesn't work. I'm going ti test everything again in an emulator and a local server.
> 
> 
> 
> In what way does it not work?

Sorry I will give you a full report of the testing once I get to the office (in ~2 hours)z

**Comment by shankari** [comment]
This has not be tested, but the intent is that changing all surveyOptions to ENKETO and setting the analysis key on the server should be enough to switch implementations.

**Comment by asiripanich** [comment]
Just realised that I forgot to purge the analysis database before doing this
> Testing the fix right now. I just reset the pipeline state and re-running the pipeline intake.

**Comment by asiripanich** [comment]
I'm waiting for the pipeline to finish. However, I'm seeing a lot of this no match warning.

```
2022-10-20T23:57:39.719330+00:00**********UUID XXXX: updating incoming user inputs**********
No match found for user input Entry({'_id': ObjectId('633f7587f6694ea8a722f1df'), 'user_id': UUID('XXXX'), 'metadata': {'time_zone': 'Australia/Sydney', 'plugin': 'none', 'write_ts': 1665064249.61109, 'platform': 'ios', 'read_ts': 0, 'key': 'manual/trip_user_input', 'type': 'message', 'write_local_dt': {'year': 2022, 'month': 10, 'day': 7, 'hour': 0, 'minute': 50, 'second': 49, 'weekday': 4, 'timezone': 'Australia/Sydney'}, 'write_fmt_time': '2022-10-07T00:50:49.611090+11:00'}, 'data': {'end_ts': 1665053698.613543,
```

**Comment by shankari** [comment]
```
2022-10-20T23:57:39.719330+00:00**********UUID XXXX: updating incoming user inputs**********
```

is expected - if you have reset the pipeline, there are no confirmed trips to match the user inputs against

**Comment by asiripanich** [comment]
> ```
> 2022-10-20T23:57:39.719330+00:00**********UUID XXXX: updating incoming user inputs**********
> ```
> 
> is expected - if you have reset the pipeline, there are no confirmed trips to match the user inputs against

Does this mean I need to run the pipeline again to match the user inputs to confirmed trips made from the first pipeline run?

**Comment by asiripanich** [comment]
Also is this normal? 

```
Cleaning and resampling failed for user XXXX
Traceback (most recent call last):
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 84, in clean_and_resample
    last_raw_place = save_cleaned_segments_for_ts(user_id, time_query.startTs, time_query.endTs)
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 110, in save_cleaned_segments_for_ts
    return save_cleaned_segments_for_timeline(user_id, tl)
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 136, in save_cleaned_segments_for_timeline
    (last_cleaned_place, filtered_tl) = create_and_link_timeline(tl, user_id, trip_map)
  File "/usr/src/app/emission/analysis/intake/cleaning/clean_and_resample.py", line 967, in create_and_link_timeline
    link_trip_start(ts, curr_cleaned_trip, curr_cleaned_start_place, raw_start_place)
```

**Comment by shankari** [comment]
> Does this mean I need to run the pipeline again to match the user inputs to confirmed trips made from the first pipeline run? If that is the case, shouldn't this be run after the confirmed trip step?

No. Context: https://github.com/e-mission/e-mission-server/pull/780 and https://github.com/e-mission/e-mission-docs/issues/476#issuecomment-561727669

**Comment by shankari** [comment]
`Cleaning and resampling failed for user XXXX` shouldn't happen, but just the traceback doesn't tell me enough about the impact. Can you look at the logs to see what the reason was and whether it affected other steps?

**Comment by shankari** [comment]
Also btw resetting the pipeline state will purge the analysis database. Is this not what you are seeing?
How are you resetting the pipeline?

**Comment by asiripanich** [comment]
> Also btw resetting the pipeline state will purge the analysis database. Is this not what you are seeing? How are you resetting the pipeline?

I did the followings:

1) ./e-mission-py.bash bin/purge_analysis_database.py
2) ./e-mission-py.bash bin/reset_pipeline.py -e XXXX
3) ./e-mission-py.bash bin/debug/intake_single_user.py -e XXXX

**Comment by shankari** [comment]
In those steps, you don't need the `./e-mission-py.bash bin/purge_analysis_database.py` because resetting the pipeline will also delete all entries. Did you get any errors while resetting the pipeline?

**Comment by asiripanich** [comment]
> In those steps, you don't need the `./e-mission-py.bash bin/purge_analysis_database.py` because resetting the pipeline will also delete all entries. Did you get any errors while resetting the pipeline?

Do you have time for a quick zoom call to go over this with me? Maybe more efficient to fix it that way and I will document the steps for the PR.

**Comment by asiripanich** [comment]
After all those steps I'm still seeing the labels and not the ENKETO objects in the user_input field.

image

Here is the server code that we modified:

```r
        if confirmed_trip is not None:
            input_name = obj_to_dict_key(ui.metadata.key)
            logging.info("Input_name is: %s" % input_name)
            confirmed_trip["data"]["user_input"][input_name] = ui # i removed the if else statement just to make sure `input_name` is not wrong.
```

**Comment by shankari** [comment]
the changes to the code only change the field in the confirmed trip.
What are you showing here? Are they fields in the confirmed trip, or the `manual/trip_user_input` objects?
I am not sure what software you are using to see it

**Comment by asiripanich** [comment]
> In those steps, you don't need the `./e-mission-py.bash bin/purge_analysis_database.py` because resetting the pipeline will also delete all entries. Did you get any errors while resetting the pipeline?

This is what I got from resetting the pipeline:

```
(emission) root@12332dea4b43:/usr/src/app# ./e-mission-py.bash bin/reset_pipeline.py -e XXXX
URL not formatted, defaulting to "Stage_database"
Connecting to database URL db
Namespace(all=False, date=None, dry_run=False, email_list=['Roger728'], platform=None, user_list=None)
INFO:root:received list with [UUID('XXXX')] users
INFO:root:first few entries are [UUID('XXXX')]
INFO:root:resetting user XXXX to start
INFO:root:About to delete 2172 analysis results
INFO:root:About to delete entries with keys ['analysis/cleaned_place', 'analysis/cleaned_section', 'analysis/cleaned_stop', 'analysis/cleaned_trip', 'analysis/cleaned_untracked', 'analysis/confirmed_trip', 'analysis/expected_trip', 'analysis/inferred_labels', 'analysis/inferred_section', 'analysis/inferred_trip', 'analysis/recreated_location', 'analysis/smoothing', 'inference/labels', 'inference/prediction', 'segmentation/raw_place', 'segmentation/raw_section', 'segmentation/raw_stop', 'segmentation/raw_trip', 'segmentation/raw_untracked']
INFO:root:About to delete 11 pipeline states
INFO:root:this is not a dry run, result of removing analysis objects = {'n': 2172, 'ok': 1.0}
INFO:root:this is not a dry run, result of removing pipeline states = {'n': 11, 'ok': 1.0}
```

**Comment by asiripanich** [comment]
> What are you showing here? Are they fields in the confirmed trip, or the `manual/trip_user_input` objects?

They are from the confirmed_trips objects.

**Comment by shankari** [comment]
sure, send me the link over email

**Comment by shankari** [comment]
@asiripanich now that this works, can you please update the PR and include a unit test?

**Comment by asiripanich** [comment]
> @asiripanich now that this works, can you please update the PR and include a unit test?

Working on it. ;)

**Comment by shankari** [comment]
We just ran the code 😄 But I would suggest creating unit tests to ensure that it continues working.

**Comment by asiripanich** [comment]
> We just ran the code 😄 But I would suggest creating unit tests to ensure that it continues working.

I'm learning how unit testing works python. I guess I will need to generate new test data to test this fix as well.

**Comment by shankari** [comment]
There's already a unit test for input matching that loads some test data. You should be able to build on the existing tests and  load a different type of user input.

**Comment by asiripanich** [comment]
@shankari i think it is ready to be reviewed. :)

**Review by shankari — APPROVED** [review]
LGTM!

**Pull request merged**
