### PR TITLE
Fix some embedded links by changing them to the new URL format

### PR DESCRIPTION
**Pull request by shankari**
And remove the fullpage link to the last card by converting it to a mailto: link

### CODE REVIEW

**Comment by shankari** [comment]
@sunil07t, I just made some more minor fixes.
Let me know when you are doing with screenshots so that I can deploy!

**Comment by sunil07t** [comment]
I took the screenshots

**Comment by shankari** [comment]
jenkins, test this please

**Comment by shankari** [comment]
The failure is not related to this change, which does not touch any python code. The underlying issue needs to be investigated and fixed, but doesn't need to hold up other changes.

**Comment by shankari** [comment]
I will investigate and fix the underlying issue once I get some breathing room from the theory paper.

**Pull request merged**
