### PR TITLE
Updated the suggestion functions to output the alias for Trevor's function

### PR DESCRIPTION
**Pull request by valin1**
I also updated the wording of suggestions so they wouldn't be that harsh to the people receiving the suggestions. Trevor should be able to get reviews now through the business_id using the aliases.

### CODE REVIEW

**Comment by shankari** [comment]
Please indicate testing done

**Comment by valin1** [comment]
{'businessid': 'mr-mamas-las-vegas-7',
 'message': "We saw that you took a vehicle from (removed address for privacy) to 89130, United States of America. Instead, there is a place Mr Mamashas better reviews, closer to your original starting point, and has a rating of 4.5 that you could have potentially used public transportation to get there.",
 'method': 'public',
 'rating': '4.5',
 'tripid': ObjectId('5c3ead4669afd753a2b9a5ad')}

**Comment by shankari** [comment]
> Mr Mamashas better reviews
 Mr Mamashas **has** better reviews?

**Comment by valin1** [comment]
Updated the grammar of the suggestions.

**Comment by shankari** [comment]
Please revert your changes to `Timeseries_sample.ipynb`

**Comment by shankari** [comment]
I'm going to merge with squash to since there have been a lot of very small changes and one revert.

**Pull request merged**
