### PR TITLE
Fixes from production

### PR DESCRIPTION
**Pull request by shankari**
@shanthistyle, @sdsingh, @joshzarrabi, @jimmydief @zacatac 
Here are the changes that I needed to make to get everything to "work" on production.

Since you wrote the code, I'd appreciate a code review - that will also allow you to understand the changes as you start working on them over the summer. It will also give you experience with code reviews :)

I write detailed comments for my commits, so you might want to look at the commits to understand the rationale for the changes.

### CODE REVIEW

**Comment by shankari** [comment]
The second round of test failures are because of a setup issue in the automatic build. The tests all pass on my laptop. Waiting for Shane to fix the setup before merging.

Also waiting for some code reviews - @joshzarrabi or @sfwatergit might be the first to look at it?

**Comment by joshzarrabi** [comment]
Hi,

I'm going to visit family in Los Angeles for the weekend but I will check
it out first thing on Tuesday.

Josh

**Comment by shankari** [comment]
@sfwatergit, thank you for the detailed comments! I've responded to all of them now. Please let me know if you would like additional clarification on any of them.

**Comment by shankari** [comment]
jenkins, test this please

**Comment by shankari** [comment]
Now that this passes tests, I am going to merge it right now, and will address Josh's comments in a later set of changes.

**Pull request merged**
