### PR TITLE
Switch the suggestion system API methods to use the stored business id if it exists

### PR DESCRIPTION
**Pull request by shankari**
Both the single trip and the general API now look up the `destination_confirm` object, and only if it exists, return a suggestion.

This required a couple of other changes:
- minor change: renamed `cleaned_trip` to `cleaned_trips` in `calculate_yelp_server_suggestion_singletrip_nominatim` since we have retrieved one trip, not a list of trips. Meaningful variable names are important!
- more substantial change: changed the data access method for the list of cleaned trips from `get_data_df` to `find_entries`. Rationale:
- we weren't using the dataframe functionality, and were just iterating through the list of trips anyway
- the function to lookup the `destination_confirm` object requires a trip entry. I could look up the trip object using the id from the dataframe, but that is an additional lookup, and one that is unnecessary if we change the retrieval method

because of this change, we read the fields of the trip object differently, but the changes should be pretty straightforward; essentially find/replace

Testing done:
Added new integration tests
All 5 tests pass

@valin @sam11b, please check the expected behavior of the suggestion function if it doesn't find any trips with valid suggestions. What does the UX expect?

### CODE REVIEW

**Comment by shankari** [comment]
Testing results for the record

```
./e-mission-py.bash emission/integrationTests/suggestionsys/TestSuggestionSys.py
----------------------------------------------------------------------
Ran 5 tests in 18.098s

OK
```

**Comment by valin1** [comment]
Looks good to me.

**Comment by shankari** [comment]
> @valin @sam11b, please check the expected behavior of the suggestion function if it doesn't find any trips with valid suggestions. What does the UX expect?

We currently return None (see last test case). Not sure if that is what the UX expects? I am happy to change this, but I need to know the expected behavior of the interface.

**Comment by shankari** [comment]
Merging this for now so we have at least the basic implementation available.

**Pull request merged**
