### PR TITLE
Fix delete user by removing it since the actual new script is purge user

### PR DESCRIPTION
**Pull request by shankari**
Testing done:

```
$ ./e-mission-py.bash bin/debug/load_timeline_for_day_and_user.py emission/tests/data/real_examples/urap_student_car_as_bike_2018-03-07 test_physical_phone_api_26
Connecting to database URL localhost
emission/tests/data/real_examples/urap_student_car_as_bike_2018-03-07
Loading file emission/tests/data/real_examples/urap_student_car_as_bike_2018-03-07
After registration, test_physical_phone_api_26 -> e934389c-471a-4c1f-8c40-cf54cf63a02b
Finished loading 0 entries into the usercache and 1153 entries into the timeseries
```

```
$ ./e-mission-py.bash bin/debug/intake_single_user.py -e test_physical_phone_api_26
Connecting to database URL localhost
analysis.debug.conf.json not configured, falling back to sample, default configuration
google maps key not configured, falling back to nominatim
nominatim not configured either, place decoding must happen on the client
2019-03-24T15:43:51.558662-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: moving to long term**********
2019-03-24T15:43:51.576502-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: filter accuracy if needed**********
2019-03-24T15:43:51.652072-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: segmenting into trips**********
2019-03-24T15:43:57.013026-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: segmenting into sections**********
2019-03-24T15:43:57.489346-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: smoothing sections**********
/Users/shankari/OSS/anaconda/envs/emission/lib/python3.6/site-packages/pandas/core/frame.py:891: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  "columns will be omitted.", UserWarning)
2019-03-24T15:43:57.881410-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: cleaning and resampling timeline**********
2019-03-24T15:43:59.351192-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: inferring transportation mode**********
2019-03-24T15:43:59.565862-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: checking active mode trips to autocheck habits**********
2019-03-24T15:43:59.568861-07:00**********UUID e934389c-471a-4c1f-8c40-cf54cf63a02b: storing views to cache**********
```

```
$ ./e-mission-ipy.bash
Python 3.6.1 | packaged by conda-forge | (default, May 11 2017, 18:00:28)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import emission.core.get_database as edb
Connecting to database URL localhost

In [2]: edb.get_uuid_db().find().count()
Out[2]: 1

In [3]: edb.get_timeseries_db().count()
Out[3]: 1162

In [4]: edb.get_analysis_timeseries_db().count()
Out[4]: 245

In [5]:
Do you really want to exit ([y]/n)? y
```

```
$ git cherry-pick a374683270d14f36ca9f776b1d9ae9d58816ef67
[fix_delete_user 53522a61] Finish pending merge so that we can fix `delete_user`
 Date: Sun Mar 24 14:41:45 2019 -0700
 4 files changed, 46 insertions(+), 42 deletions(-)
$ ./e-mission-py.bash bin/debug/purge_user.py -e test_physical_phone_api_26
Connecting to database URL localhost
INFO:root:For uuid = e934389c-471a-4c1f-8c40-cf54cf63a02b, deleting entries from the timeseries
DEBUG:root:db_array not passed in, looking up databases
INFO:root:result = {'n': 1162, 'ok': 1.0}
INFO:root:For uuid = e934389c-471a-4c1f-8c40-cf54cf63a02b, deleting entries from the analysis_timeseries
INFO:root:result = {'n': 245, 'ok': 1.0}
INFO:root:For uuid e934389c-471a-4c1f-8c40-cf54cf63a02b, deleting entries from the user_db
INFO:root:result = {'n': 1, 'ok': 1.0}
```

### CODE REVIEW

**Comment by shankari** [comment]
It turned out that I was right about a374683270d14f36ca9f776b1d9ae9d58816ef67 fixing the issue, it is just that it was for `purge_user` and not `delete_user`. I cherry-picked the commit to this branch to make the script work.

This fixes https://github.com/e-mission/e-mission-docs/issues/338

**Comment by PatGendre** [comment]
thanks a lot!

**Comment by PatGendre** [comment]
Hi, sorry I just cannot find the purge_user.py file, it is not in master nor in your fix_delete_user branch?

**Comment by shankari** [comment]
Argh! I had forgotten to add some files.
Should be fixed in https://github.com/e-mission/e-mission-server/pull/643

**Comment by PatGendre** [comment]
thank you, it works well with -e user_email :-)
however I could not use it with the -u option, it seems that the uuid line 20 should be declared somewhere in purge_user.py?

**Pull request merged**
