### PR TITLE
Add the common trips tab

### PR DESCRIPTION
**Pull request by shankari**
Changes:
- Tabs for the new common trips
- Changes to canonical trip generation and parsing to return a single representative trip

### CODE REVIEW

**Comment by shankari** [comment]
@zacatac, there were a lot of overlaps between your code and code that I had changed yesterday, so I spent some time pulling your changes out separately. I'm going to merge this and deploy to the server once I get into Soda (I am at MacArthur now). Fingers crossed that it works - will back out if not.

**Comment by zacatac** [comment]
Awesome! Thanks Shankari!



—

**Comment by zacatac** [comment]
WOOOO!

**Comment by shankari** [comment]
Yeah! I just needed 20 min to fix it, but unfortunately, I didn't have 20 min at that time.
Merging now, and will push to the server tonight.

**Pull request merged**
