### PR TITLE
change similarity code

### PR DESCRIPTION
**Pull request by corinne-hcr**

### CODE REVIEW

**Comment by shankari** [comment]
Why does this PR have the commit https://github.com/e-mission/e-mission-server/pull/799/commits/b125cd019ab0f8fe51aaa023fdcc63457e6dcfd9

Hasn't that already been committed in 
https://github.com/e-mission/e-mission-server/commit/f4ed2a7cca31410e01bc2ffde26822fe28e1b78e?

**Comment by shankari** [comment]
Did you handle the squash-merge correctly?

**Comment by corinne-hcr** [comment]
I used an old branch to commit `87a41d9`
I saw there were some old commits after I started this PR, I thought that was due to the old branch.
Should I use a new branch?

**Comment by shankari** [comment]
>  Should I close this PR and use a new branch?

Yes.

**Pull request closed without merging**
