### PR TITLE
Configuring PYTHON_LEGACY UUID representation in cfc_webapp.py

### PR DESCRIPTION
**Pull request by swastis10**
We cannot encode native uuid.UUID with UuidRepresentation.UNSPECIFIED therefore defining uuid_representation as PYTHON_LEGACY fixes the issue 
Contains fix for - https://github.com/e-mission/e-mission-docs/issues/856#issuecomment-1464579523

### CODE REVIEW

**Comment by swastis10** [comment]
The test data is now being loaded fine by the local server on the UI.
Screen Shot 2023-03-10 at 7 48 07 PM

**Comment by shankari** [comment]
@swastis10 I don't think we should edit `bottle.py` directly since it is a dependency and not our code
I would use the approach outlined in https://github.com/bottlepy/bottle/issues/287

Note that I already do this in `cfc_webapp.py`, similar to the suggestions in the issue above

```
    for plugin in app.plugins:
        if isinstance(plugin, JSONPlugin):
            print("Replaced json_dumps in plugin with the one from bson")
            plugin.json_dumps = bson.json_util.dumps
```

You just need to change it to `plugin.json_dumps = lambda s: bju.dumps(...)`

**Comment by swastis10** [comment]
The data is still loading fine, just like the screenshot attached above.

**Review by shankari — APPROVED** [review]
LGTM! Will merge and deploy after the tests finish running

**Pull request merged**
