### PR TITLE
Fix 404 redirect

### PR DESCRIPTION
**Pull request by sblaisot**
This PR fixes 404 redirect by replacing hardcoded redirect URI with configured redirect URI, should it exist in configuration.

I also simplified how redirect_uri is retrieved from configuration with getter and default value.

### CODE REVIEW

**Review by shankari — APPROVED** [review]
Code changes look fine to me.

@sblaisot thanks for the contribution!
Can you also indicate the testing done, potentially with a small video since there is not a unit test for this functionality?

**Comment by sblaisot** [comment]
Hi @shankari 

I just added unit test for the 404 redirect

**Comment by sblaisot** [comment]
Launching this test on current master:

```
F
======================================================================
FAIL: test404Redirect (netTests.TestWebserver.TestWebserver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/openpath/e-mission-server/emission/tests/netTests/TestWebserver.py", line 57, in test404Redirect
    self.assertEqual(response.get_header("Location"), "http://somewhere.else")
AssertionError: 'https://www.nrel.gov/transportation/openpath.html' != 'http://somewhere.else'
- https://www.nrel.gov/transportation/openpath.html
+ http://somewhere.else


----------------------------------------------------------------------
Ran 1 test in 0.786s
```

Running this test on this PR's source branch:

```
.
----------------------------------------------------------------------
Ran 1 test in 0.751s

OK
```

**Comment by shankari** [comment]
@aGuttman not sure if you have written the unit test for https://github.com/e-mission/e-mission-server/pull/886 yet, but @sblaisot has already written the first unit test for the API, so you should be able to add yours to this file as well.

**Pull request merged**
