### PR TITLE
Changes made in server for generating maps

### PR DESCRIPTION
**Pull request by yw374cornell**

### CODE REVIEW

**Comment by shankari** [comment]
I'll merge and test this, but just FYI:
- this is still from master
- it includes a change that we definitely don't want to commit (hardcoding the a path with your name)

I'll pull and try to experiment with this on the weekend - I want to get the metrics calculation in place for now

**Comment by yw374cornell** [comment]
oh right.. That was a temporary workaround before I got the python path set up correctly. I should have changed it back. Thanks for resolving that for me!

**Comment by yw374cornell** [comment]
actually, I have reverted changes made on master and pulled from upstream if you looked at the latest commits. I created a separate branch that contains the changes made in plotting files and I could create another pull request from that branch.

**Comment by shankari** [comment]
yeah I noticed that there were no files listed :)
would be great to send a PR from the other branch when free

**Pull request merged**
