### PR TITLE
Fix deployment errors

### PR DESCRIPTION
**Pull request by shankari**
Fix a bunch of issues uncovered while pushing the changes to the server.
@jesca, @shanthistyle, can you review my fixes and ensure that they match your vision for the change?
I'm going to merge this tonight and deploy to the server.

### Smoothing change ###
- Disable the smoothing since it has several issues with imports and missing variables
    
### Validation change ###

- Ensure that the library based validation works for ios and android client keys
- Update the documentation to address some setup issues with the new library
    
### User specific carbon footprint change ###
- pass in the uuid versus user objects correctly otherwise we try to query the database with a user object instead of a user_uuid object.
- correct the calculation of the default MPG. The default _footprint_ was being used instead, which meant that the footprint in the map was calculated using the wrong MPG and was off by a lot.
- unified the interface to the carbon module.  We now always pass in the uuid, never the user directly. This allows us to avoid confusion in what we are passing in, and subtle errors later

### Misc ###
- Fixed an import in modeshare
- Added some floats to TestGamified. Shouldn't make a difference, but better to be safe.
- Fixed testGamified to compare to a reasonable level of precision since we are performing floating point arithmetic
- Fixed test cases to always pass in UUID to the carbon code

### CODE REVIEW

**Comment by shanthistyle** [comment]
Yes, the user specific carbon foorprint changes look good to me, including
passing in the uuid

On Mon, Mar 2, 2015 at 4:10 PM, shankari <notifications@github.com> wrote:

> Fix a bunch of issues uncovered while pushing the changes to the server.
> @jesca <https://github.com/jesca>, @shanthistyle
> <https://github.com/shanthistyle>, can you review my fixes and ensure
> that they match your vision for the change?
> I'm going to merge this tonight and deploy to the server.
> Smoothing change
>
>    - Disable the smoothing since it has several issues with imports and
>    missing variables
>
> Validation change
>
>    - Ensure that the library based validation works for ios and android
>    client keys
>    - Update the documentation to address some setup issues with the new
>    library
>
> User specific carbon footprint change
>
>    - pass in the uuid versus user objects correctly otherwise we try to
>    query the database with a user object instead of a user_uuid object.
>    - correct the calculation of the default MPG. The default *footprint*
>    was being used instead, which meant that the footprint in the map was
>    calculated using the wrong MPG and was off by a lot.
>    - unified the interface to the carbon module. We now always pass in
>    the uuid, never the user directly. This allows us to avoid confusion in
>    what we are passing in, and subtle errors later
>
> Misc
>
>    - Fixed an import in modeshare
>    - Added some floats to TestGamified. Shouldn't make a difference, but
>    better to be safe.
>    - Fixed testGamified to compare to a reasonable level of precision
>    since we are performing floating point arithmetic
>    - Fixed test cases to always pass in UUID to the carbon code
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/e-mission/e-mission-server/pull/100
> Commit Summary
>
>    - Fix a bunch of issues uncovered during the latest server deployment
>    - Unified the interface to the carbon module
>
> File Changes
>
>    - *M* CFC_DataCollector/moves/collect.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-0>
>    (6)
>    - *M* CFC_WebApp/api/cfc_webapp.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-1>
>    (32)
>    - *M* CFC_WebApp/clients/default/default.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-2>
>    (1)
>    - *M* CFC_WebApp/clients/gamified/gamified.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-3>
>    (6)
>    - *M* CFC_WebApp/dao/user.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-4>
>    (13)
>    - *M* CFC_WebApp/main/carbon.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-5>
>    (31)
>    - *M* CFC_WebApp/main/modeshare.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-6>
>    (3)
>    - *M* CFC_WebApp/tests/client_tests/TestDefault.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-7>
>    (2)
>    - *M* CFC_WebApp/tests/client_tests/TestGamified.py
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-8>
>    (17)
>    - *M* README.md
>    <https://github.com/e-mission/e-mission-server/pull/100/files#diff-9>
>    (17)
>
> Patch Links:
>
>    - https://github.com/e-mission/e-mission-server/pull/100.patch
>    - https://github.com/e-mission/e-mission-server/pull/100.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-mission/e-mission-server/pull/100>.
>



-- 
Shanthi Shanmugam

Third Year Undergraduate
University of California, Berkeley
B.S. Electrical Engineering & Computer Science
shanthi@berkeley.edu

**Comment by shankari** [comment]
Pretty big oops on the default MPG calculation :)
Figured it out while running the gamification tests.
I'm going to push for runAllTests more strongly this Thursday.

**Comment by shanthistyle** [comment]
What was the mistake?



—

**Comment by shankari** [comment]
You had the defaultMpg = 92/1609.

First, the carbon footprint for the *train* mode is 92/1609 - for car it is more like 278/1609.
The *optimal* carbon footprint for long car trips is 92/1609 because the optimal replacement for a long car trip is a long train trip.

Second, even 278/1609 is the *carbon footprint*. Recall that we convert mpg to carbon footprint by using the carbon/gallon number. So using 278/1609 as the average *mpg* messed up all the calculations because we tried to apply the conversions to it to get the carbon footprint.

**Pull request merged**
