### PR TITLE
Add integration tests to create an artificial dataset for the suggest…

### PR DESCRIPTION
**Pull request by shankari**
…ion system components

- README with instructions on how to generate the test cases
- test harness with wrappers for the three main algorithms
- dataset files with one sample entry, corresponding to a trip from a suburban
  residential area to a suburban big box store, where there is a closer store available

Note that the destination is not currently detected correctly so the accuracy is 0%

Testing done

Arguments
---------

```
$ ./e-mission-py.bash -d emission/integrationTests/suggestionsys/algorithm_test_harness.py
Connecting to database URL localhost
usage: algorithm_test_harness.py [-h] [-f INFILE]
                                 {find_destination_business,category_of_business_nominatim,calculate_yelp_server_suggestion_for_locations}
algorithm_test_harness.py: error: the following arguments are required: algorithm
```

`find_destination_business`
---------

```
(emission) C02KT61MFFT0:e-mission-server shankari$ ./e-mission-py.bash -d emission/integrationTests/suggestionsys/algorithm_test_harness.py find_destination_business
Connecting to database URL localhost
INFO:root:Mapped algorithm find_destination_business -> <function test_find_destination_business at 0x109262bf8>
DEBUG:root:-----Mountain View Kohls------
DEBUG:root:parsed_response = {'place_id': '201857', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'osm_type': 'way', 'osm_id': '5066896', 'lat': '37.4030262', 'lon': '-122.1102601', 'display_name': 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'address': {'road': 'Pacchetti Way', 'neighbourhood': 'Castro City', 'city': 'Mountain View', 'county': 'Santa Clara County', 'postcode': '94023', 'country': 'United States of America', 'country_code': 'us'}}
DEBUG:root:Nominatim found destination business ('Pacchetti Way', 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'Mountain View', False)
DEBUG:root:Test Mountain View Kohls failed, output = ['Pacchetti Way', 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'Mountain View', False], expected ["Kohl's", 'Showers Drive', 'Mountain View', True]
DEBUG:root:After instance Mountain View Kohls, successfulTests = 0, failedTests = 1
INFO:root:Test complete, overall accuracy = 0.0
```

`category_of_business_nominatim`
---------

```
$ ./e-mission-py.bash -d emission/integrationTests/suggestionsys/algorithm_test_harness.py category_of_business_nominatim
Connecting to database URL localhost
INFO:root:Mapped algorithm category_of_business_nominatim -> <function test_category_of_business_nominatim at 0x1135ec8c8>
DEBUG:root:-----Mountain View Kohls------
DEBUG:root:parsed_response = {'place_id': '201857', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'osm_type': 'way', 'osm_id': '5066896', 'lat': '37.4030262', 'lon': '-122.1102601', 'display_name': 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'address': {'road': 'Pacchetti Way', 'neighbourhood': 'Castro City', 'city': 'Mountain View', 'county': 'Santa Clara County', 'postcode': '94023', 'country': 'United States of America', 'country_code': 'us'}}
DEBUG:root:Nominatim found destination business ('Pacchetti Way', 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'Mountain View', False)
DEBUG:root:Test Mountain View Kohls failed, output = [], expected ['deptstores', 'menscloth', 'womenscloth']
DEBUG:root:After instance Mountain View Kohls, successfulTests = 0, failedTests = 1
INFO:root:Test complete, overall accuracy = 0.0
```

`calculate_yelp_server_suggestion_for_locations`
.......................

```
$ ./e-mission-py.bash -d emission/integrationTests/suggestionsys/algorithm_test_harness.py calculate_yelp_server_suggestion_for_locations
Connecting to database URL localhost
INFO:root:Mapped algorithm calculate_yelp_server_suggestion_for_locations -> <function test_calculate_yelp_server_suggestion_for_locations at 0x11805f950>
DEBUG:root:-----Sunnyvale -> Mountain View Kohls------
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.mapquestapi.com
DEBUG:requests.packages.urllib3.connectionpool:http://www.mapquestapi.com:80 "GET /directions/v2/route?key=AuwuGlPC5f3Ru7PGahKAtGcs4WdvARem&from=37.3635335,-122.0154871&to=37.40355,-122.10783 HTTP/1.1" 200 None
DEBUG:root:distance in meters = 11695.106466185258
DEBUG:root:parsed_response = {'place_id': '201857', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'osm_type': 'way', 'osm_id': '5066896', 'lat': '37.4030262', 'lon': '-122.1102601', 'display_name': 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'address': {'road': 'Pacchetti Way', 'neighbourhood': 'Castro City', 'city': 'Mountain View', 'county': 'Santa Clara County', 'postcode': '94023', 'country': 'United States of America', 'country_code': 'us'}}
DEBUG:root:Nominatim found destination business ('Pacchetti Way', 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'Mountain View', False)
DEBUG:root:parsed_response = {'place_id': '268772', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'osm_type': 'way', 'osm_id': '8932529', 'lat': '37.3638317', 'lon': '-122.0170368', 'display_name': 'Gladiola Drive, Sunnyvale, Santa Clara County, 94086, United States of America', 'address': {'road': 'Gladiola Drive', 'city': 'Sunnyvale', 'county': 'Santa Clara County', 'postcode': '94086', 'country': 'United States of America', 'country_code': 'us'}}
DEBUG:root:parsed_response = {'place_id': '201857', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'osm_type': 'way', 'osm_id': '5066896', 'lat': '37.4030262', 'lon': '-122.1102601', 'display_name': 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'address': {'road': 'Pacchetti Way', 'neighbourhood': 'Castro City', 'city': 'Mountain View', 'county': 'Santa Clara County', 'postcode': '94023', 'country': 'United States of America', 'country_code': 'us'}}
DEBUG:root:parsed_response = {'place_id': '201857', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'osm_type': 'way', 'osm_id': '5066896', 'lat': '37.4030262', 'lon': '-122.1102601', 'display_name': 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'address': {'road': 'Pacchetti Way', 'neighbourhood': 'Castro City', 'city': 'Mountain View', 'county': 'Santa Clara County', 'postcode': '94023', 'country': 'United States of America', 'country_code': 'us'}}
DEBUG:root:parsed_response = {'place_id': '201857', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'osm_type': 'way', 'osm_id': '5066896', 'lat': '37.4030262', 'lon': '-122.1102601', 'display_name': 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'address': {'road': 'Pacchetti Way', 'neighbourhood': 'Castro City', 'city': 'Mountain View', 'county': 'Santa Clara County', 'postcode': '94023', 'country': 'United States of America', 'country_code': 'us'}}
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/Pacchetti-Way-Mountain%20View HTTP/1.1" 400 186
DEBUG:root:parsed_response = {'place_id': '201857', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright', 'osm_type': 'way', 'osm_id': '5066896', 'lat': '37.4030262', 'lon': '-122.1102601', 'display_name': 'Pacchetti Way, Castro City, Mountain View, Santa Clara County, 94023, United States of America', 'address': {'road': 'Pacchetti Way', 'neighbourhood': 'Castro City', 'city': 'Mountain View', 'county': 'Santa Clara County', 'postcode': '94023', 'country': 'United States of America', 'country_code': 'us'}}
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.yelp.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.yelp.com:443 "GET /v3/businesses/search?location=Pacchetti%2BWay%2C%2BCastro%2BCity%2C%2BMountain%2BView%2C%2BSanta%2BClara%2BCounty%2C%2B94023%2C%2BUnited%2BStates%2Bof%2BAmerica HTTP/1.1" 200 None
DEBUG:root:Test Sunnyvale -> Mountain View Kohls failed, output = None, expected target-sunnyvale-2
DEBUG:root:After instance Sunnyvale -> Mountain View Kohls, successfulTests = 0, failedTests = 1
INFO:root:Test complete, overall accuracy = 0.0
```

### CODE REVIEW

**Comment by shankari** [comment]
@b-i-l-l-c-a-o @valin1 can both of you review this harness? @b-i-l-l-c-a-o in particular, is the README clear?

**Comment by valin1** [comment]
For the first mark down, algorithm_test_harness.py: error: the following arguments are required: algorithm, is the extra argument that needs to be added the test data?

**Comment by shankari** [comment]
@valin1 not sure what your comment means - the successful runs show how to run the script without an error by passing in the algorithm as an argument

**Comment by shankari** [comment]
The current case (Kohl's) may never work
https://github.com/e-mission/e-mission-docs/issues/382#issuecomment-485050532

**Comment by shankari** [comment]
@b-i-l-l-c-a-o merged. you should be able to pull and start filling in the dataset files now. Note that for the same use case, you probably want to put entries into all three datasets

**Pull request merged**
