### PR TITLE
fulfillment on pull request request: pip with windows

### PR DESCRIPTION
**Pull request by michaelpeng**
Hello

### CODE REVIEW

**Comment by shankari** [comment]
This is fine, but is there an improvement that you can add to the README.
Maybe a link to the installation instructions on Mac OSX (right now we have only ubuntu).
Maybe some clarification on some issues that you ran into in the install?

**Comment by michaelpeng** [comment]
Added instructions on how to install and use pip with Windows. Sorry for potentially excessive commits--kept noticing little mistakes or things to improve

**Comment by shankari** [comment]
Technically, I should ask you to squash your changes, but I've found that squashing is a bit tricky to get right, so I won't insist on it at this time.

On the other hand, it would be good to learn to squash now, since the stakes are pretty low.
Let me know if you want to be ambitious or not :)

https://gun.io/blog/how-to-github-fork-branch-and-pull-request/
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by michaelpeng** [comment]
Hmm, is this how? Feel like I messed up b/c I remembered renaming the commit to "README update ..." Also either the "Merge branch 'master' of ... " is supposed to be there, or I did something wrong.

**Comment by shankari** [comment]
That looks wrong. At the end, you should have one commit, not 84 :)

**Comment by shankari** [comment]
You can just clone a new copy and submit a new pull request for now.
Because recovering from a botched squash is even worse than the original squash, IIRC.
At least now you know what doesn't work...

**Comment by michaelpeng** [comment]
Ahh sorry... I'll do that and close this request.

**Pull request closed without merging**
